"""
Stress-Tested Retrieval Quality Evaluation Benchmark (Recall@K & Hallucination Prevention)

Loads ground-truth benchmark events from `data/ground_truth_events.json` generated by `mock_data_gen.py`.
Evaluates:
1. Positive Queries (Specific, Vague, Compound) -> Recall@3, Recall@5
2. Negative / Non-Existent Queries ("yellow card", "VAR handball") -> Measures relevance score distance / hallucination suppression.
"""

import json
from pathlib import Path
from src.event_extraction.parser import parse_tracking_json
from src.event_extraction.preprocessor import TrackingPreprocessor
from src.event_extraction.heuristics import EventExtractor
from src.rag.chunker import EventAdaptiveChunker
from src.rag.vector_store import VectorStoreManager
from src.rag.retriever import EventRetriever


def run_retrieval_quality_evaluation(
    tracking_path: str = "data/sample_tracking.json",
    ground_truth_path: str = "data/ground_truth_events.json"
):
    """
    Stress-tested evaluation running 10 benchmark queries across specific positive, vague, compound, and negative queries.
    """
    print("\n" + "=" * 70)
    print("      SOCCER MULTIMODAL RAG - STRESS-TESTED RETRIEVAL EVALUATION")
    print("=" * 70)

    # 1. Parse & Preprocess
    print("[1/4] Parsing & Preprocessing Tracking Data...")
    frames = parse_tracking_json(tracking_path)
    preprocessor = TrackingPreprocessor()
    frames = preprocessor.preprocess(frames)
    possessions = preprocessor.compute_smoothed_possessions(frames)
    pressing = preprocessor.compute_smoothed_pressing_states(frames, possessions)

    # 2. Extract Events & Chunk
    print("[2/4] Extracting Events & Adaptive Semantic Chunking...")
    extractor = EventExtractor()
    events = extractor.extract_events(frames, possessions, pressing)
    chunker = EventAdaptiveChunker()
    docs = chunker.chunk_events(events)

    # 3. Index Documents in Vector Store
    print("[3/4] Indexing Events in Chroma Vector DB...")
    vstore_mgr = VectorStoreManager(persist_directory="data/test_chroma_db", collection_name="eval_collection")
    vstore = vstore_mgr.index_documents(docs, reset=True)
    retriever = EventRetriever(vector_store=vstore, documents=docs)

    # 4. Load Ground Truth Benchmark
    gt_file = Path(ground_truth_path)
    if not gt_file.exists():
        print(f"[!] Ground truth file missing at: {gt_file}")
        return {}

    with open(gt_file, "r", encoding="utf-8") as f:
        ground_truth_queries = json.load(f)

    print(f"[4/4] Running Benchmark over {len(ground_truth_queries)} benchmark queries (Positive + Negative)...\n")

    pos_hits_r3 = 0
    pos_hits_r5 = 0
    total_pos = 0

    neg_correct = 0
    total_neg = 0

    for item in ground_truth_queries:
        q_id = item["id"]
        query = item["query"]
        q_type = item["type"]
        is_neg = item.get("is_negative_query", False)

        print(f"[{q_id} - {q_type.upper()}] Query: '{query}'")

        docs_with_scores = retriever.retrieve_with_scores(query, top_k=5)

        if is_neg:
            total_neg += 1
            # For negative query, check distance score threshold (Chroma L2 distance > 1.1 indicates low semantic match)
            top_score = docs_with_scores[0][1] if docs_with_scores else 999.0
            if top_score > 1.0 or not docs_with_scores:
                neg_correct += 1
                print(f"  [+] Negative Detection SUCCESS: Low similarity score ({top_score:.3f} > threshold)")
            else:
                print(f"  [-] Negative Detection WARNING: Potential weak match score ({top_score:.3f})")
        else:
            total_pos += 1
            exp_start = item["expected_start_sec"]
            exp_end = item["expected_end_sec"]

            # Check Recall@3
            hit_r3 = any(
                min(exp_end, doc.metadata.get("end_timestamp", 0.0)) - max(exp_start, doc.metadata.get("start_timestamp", 0.0)) > 0
                for doc, score in docs_with_scores[:3]
            )

            # Check Recall@5
            hit_r5 = any(
                min(exp_end, doc.metadata.get("end_timestamp", 0.0)) - max(exp_start, doc.metadata.get("start_timestamp", 0.0)) > 0
                for doc, score in docs_with_scores[:5]
            )

            if hit_r3:
                pos_hits_r3 += 1
            if hit_r5:
                pos_hits_r5 += 1

            status_str = "Recall@3: HIT | Recall@5: HIT" if hit_r3 and hit_r5 else ("Recall@3: MISS | Recall@5: HIT" if hit_r5 else "MISS")
            print(f"  [+] {status_str}")

    print("\n" + "-" * 70)
    print(" EVALUATION RESULTS SUMMARY:")
    r3_score = (pos_hits_r3 / total_pos * 100.0) if total_pos > 0 else 0.0
    r5_score = (pos_hits_r5 / total_pos * 100.0) if total_pos > 0 else 0.0
    neg_acc = (neg_correct / total_neg * 100.0) if total_neg > 0 else 0.0

    print(f"  Positive Queries Recall@3: {pos_hits_r3}/{total_pos} ({r3_score:.1f}%)")
    print(f"  Positive Queries Recall@5: {pos_hits_r5}/{total_pos} ({r5_score:.1f}%)")
    print(f"  Negative/Non-Existent Query Filter Accuracy: {neg_correct}/{total_neg} ({neg_acc:.1f}%)")
    print("=" * 70 + "\n")

    return {
        "Recall@3": round(r3_score, 1),
        "Recall@5": round(r5_score, 1),
        "NegativeFilterAccuracy": round(neg_acc, 1)
    }


def test_retrieval_quality():
    """Pytest hook."""
    metrics = run_retrieval_quality_evaluation()
    assert metrics.get("Recall@5", 0) >= 70.0


if __name__ == "__main__":
    run_retrieval_quality_evaluation()
